package cn.ksuser.auth.android.ui.theme

import androidx.compose.ui.graphics.Color

val GoldPrimaryLight = Color(0xFFFFB90F)
val GoldOnPrimaryLight = Color(0xFF2F2200)
val GoldPrimaryContainerLight = Color(0xFFFFE6A6)
val GoldOnPrimaryContainerLight = Color(0xFF402D00)
val GoldSecondaryLight = Color(0xFFA97800)
val GoldOnSecondaryLight = Color(0xFFFFFFFF)
val GoldSecondaryContainerLight = Color(0xFFFFEFD1)
val GoldOnSecondaryContainerLight = Color(0xFF3D2A00)
val GoldTertiaryLight = Color(0xFFC57D00)
val GoldOnTertiaryLight = Color(0xFFFFFFFF)
val GoldBackgroundLight = Color(0xFFF6F5F2)
val GoldSurfaceLight = Color(0xFFFFFFFF)
val GoldSurfaceVariantLight = Color(0xFFF1E9D7)
val GoldOnSurfaceLight = Color(0xFF1F1B13)
val GoldOnSurfaceVariantLight = Color(0xFF5B5344)
val GoldOutlineLight = Color(0xFF968A6F)
val GoldOutlineVariantLight = Color(0xFFD2C7AF)
val GoldErrorLight = Color(0xFFB3261E)

val GoldPrimaryDark = Color(0xFFFFCF57)
val GoldOnPrimaryDark = Color(0xFF402D00)
val GoldPrimaryContainerDark = Color(0xFF6A4D00)
val GoldOnPrimaryContainerDark = Color(0xFFFFE4A0)
val GoldSecondaryDark = Color(0xFFE4C57A)
val GoldOnSecondaryDark = Color(0xFF3D2B00)
val GoldSecondaryContainerDark = Color(0xFF5A4305)
val GoldOnSecondaryContainerDark = Color(0xFFFCE2A2)
val GoldTertiaryDark = Color(0xFFF0C35B)
val GoldOnTertiaryDark = Color(0xFF402D00)
val GoldBackgroundDark = Color(0xFF15120D)
val GoldSurfaceDark = Color(0xFF1D1912)
val GoldSurfaceVariantDark = Color(0xFF4A4232)
val GoldOnSurfaceDark = Color(0xFFF0E6D0)
val GoldOnSurfaceVariantDark = Color(0xFFD6C8AD)
val GoldOutlineDark = Color(0xFFA99874)
val GoldOutlineVariantDark = Color(0xFF4D4638)
val GoldErrorDark = Color(0xFFFFB4AB)

val GoldGradientTopLight = Color(0xFFF5F5F5)
val GoldGradientBottomLight = Color(0xFFFAFAFA)
val GoldGradientTopDark = Color(0xFF1A1A1A)
val GoldGradientBottomDark = Color(0xFF2D2D2D)

val BrandButtonGradientStart = Color(0xFFFFB90F)
val BrandButtonGradientEnd = Color(0xFFFFD966)
