package cn.ksuser.auth.android.ui.theme

import androidx.compose.ui.graphics.Color

val GoldPrimaryLight = Color(0xFFFFB90F)
val GoldOnPrimaryLight = Color(0xFF2F2200)
val GoldPrimaryContainerLight = Color(0xFFFFE3A1)
val GoldOnPrimaryContainerLight = Color(0xFF4A3400)
val GoldSecondaryLight = Color(0xFF9E7A20)
val GoldOnSecondaryLight = Color(0xFFFFFFFF)
val GoldSecondaryContainerLight = Color(0xFFFDEFC8)
val GoldOnSecondaryContainerLight = Color(0xFF3C2B00)
val GoldTertiaryLight = Color(0xFFC98A00)
val GoldOnTertiaryLight = Color(0xFFFFFFFF)
val GoldBackgroundLight = Color(0xFFFFFBF2)
val GoldSurfaceLight = Color(0xFFFFFCF7)
val GoldSurfaceVariantLight = Color(0xFFF8ECD0)
val GoldOnSurfaceLight = Color(0xFF2A2314)
val GoldOnSurfaceVariantLight = Color(0xFF6B5B37)
val GoldOutlineLight = Color(0xFF9A8658)
val GoldErrorLight = Color(0xFFB3261E)

val GoldPrimaryDark = Color(0xFFFFD56A)
val GoldOnPrimaryDark = Color(0xFF3A2A00)
val GoldPrimaryContainerDark = Color(0xFF6A4D00)
val GoldOnPrimaryContainerDark = Color(0xFFFFE8AF)
val GoldSecondaryDark = Color(0xFFE5C66D)
val GoldOnSecondaryDark = Color(0xFF3D2D00)
val GoldSecondaryContainerDark = Color(0xFF574103)
val GoldOnSecondaryContainerDark = Color(0xFFF8E0A0)
val GoldTertiaryDark = Color(0xFFF2C252)
val GoldOnTertiaryDark = Color(0xFF402D00)
val GoldBackgroundDark = Color(0xFF1A1610)
val GoldSurfaceDark = Color(0xFF1F1A12)
val GoldSurfaceVariantDark = Color(0xFF4E442E)
val GoldOnSurfaceDark = Color(0xFFF3E7CF)
val GoldOnSurfaceVariantDark = Color(0xFFD8C9A2)
val GoldOutlineDark = Color(0xFFA89261)
val GoldErrorDark = Color(0xFFF2B8B5)

val GoldGradientTopLight = Color(0xFFFFF5DC)
val GoldGradientBottomLight = Color(0xFFFFFDF7)
val GoldGradientTopDark = Color(0xFF2A220F)
val GoldGradientBottomDark = Color(0xFF17130C)
